name: simple_deployment_pipeline

on:
  push:
    branches:
      - master
  
  pull_request:
    branches: [master]
    types: [opened, synchronize]


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install 
        run: npm install  

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:8080

      - name: Deploy to heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: pokeman-samundra
          heroku_email: dhakalsamundra35@gmail.com
          healthcheck: https://pokeman-samundra.herokuapp.com/version
          checkstring: 2
          delay: 5 #By default, the delay will be 0 if you choose to not set it
          rollbackonhealthcheckfailed: true # By default, the application will not be rolled back if the healthcheck fails. in case of failure, it load back to previous version
     
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}